//@version=6
indicator("SMC Institutional PRO X", overlay = true, max_labels_count = 500, max_lines_count = 500, max_boxes_count = 500)

//=====================================================
// INPUTS
//=====================================================

groupStructure = "Market Structure"

swingLength = input.int(5, "Swing Length", minval = 2, group = groupStructure)

showSwings = input.bool(true, "Show Swings", group = groupStructure)

groupFilters = "Filters"

useEMA = input.bool(true, "EMA Trend Filter", group = groupFilters)

emaLength = input.int(50, "EMA Length", group = groupFilters)

useVWAP = input.bool(true, "VWAP", group = groupFilters)

groupDisplay = "Display"

bullColor = input.color(color.lime, "Bull Color", group = groupDisplay)

bearColor = input.color(color.red, "Bear Color", group = groupDisplay)


//=====================================================
// FILTERS
//=====================================================

ema = ta.ema(close, emaLength)

vwap = ta.vwap(close)

plot(useEMA ? ema : na, color=color.blue, linewidth=2, title="EMA")

plot(useVWAP ? vwap : na, color=color.orange, linewidth=2, title="VWAP")


//=====================================================
// SWING DETECTION
//=====================================================

pivotHigh = ta.pivothigh(high, swingLength, swingLength)
pivotLow = ta.pivotlow(low, swingLength, swingLength)


//=====================================================
// STORE LAST SWINGS
//=====================================================

var float previousHigh = na
var float previousLow = na

var string highType = ""
var string lowType = ""


//=====================================================
// CLASSIFY HIGHS
//=====================================================

if not na(pivotHigh)

    currentHigh = pivotHigh

    if not na(previousHigh)
        highType := currentHigh > previousHigh ? "HH" : "LH"
    else
        highType := "SH"

    previousHigh := currentHigh

    if showSwings
        label.new(
             bar_index - swingLength,
             currentHigh,
             highType,
             style = label.style_label_down,
             color = bearColor,
             textcolor = color.white)


//=====================================================
// CLASSIFY LOWS
//=====================================================

if not na(pivotLow)

    currentLow = pivotLow

    if not na(previousLow)
        lowType := currentLow > previousLow ? "HL" : "LL"
    else
        lowType := "SL"

    previousLow := currentLow

    if showSwings
        label.new(
             bar_index - swingLength,
             currentLow,
             lowType,
             style = label.style_label_up,
             color = bullColor,
             textcolor = color.white)